spring:
  datasource:
    url: jdbc:mysql://bitcoinrobot.cn:3306/sw?characterEncoding=utf8&useSSL=false
    username: root
    password: xxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true   #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      minimum-idle: 1     # 最小空闲连接数量
      maximum-pool-size: 20   # 连接池最大连接数，默认是10
      idle-timeout: 180000   # 空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 1800000   # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000  # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
      pool-name: MyHikariCP  # 连接池名字
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization.write-dates-as-timestamps: false
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sw.note.model # 扫描实例类所在包
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl